<?php

use Illuminate\Database\Seeder;
use App\Ad;

class AdsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ad::insert([
            [
                'price' => 5000.00,
                'image' => 'grxA1O6EoLpsMOWO.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 1,
                'gearbox_id' => 1,
                'body_type_id' => 1, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 1,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 1,
                'brand_id' => 3,
                'model_id' => 32,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 9000.00,
                'image' => 'u058OcakVkGZMOIg.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 1,
                'gearbox_id' => 1,
                'body_type_id' => 1, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 2,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 1,
                'brand_id' => 3,
                'model_id' => 27,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 10000.00,
                'image' => 'UsMdm6fcuHCAB9Rj.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 3,
                'gearbox_id' => 1,
                'body_type_id' => 2, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 2,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 1,
                'brand_id' => 3,
                'model_id' => 25,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 5000.00,
                'image' => 'GLpOuSnU5uv7gacA.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 1,
                'gearbox_id' => 1,
                'body_type_id' => 1, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 1,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 1,
                'brand_id' => 3,
                'model_id' => 31,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 9000.00,
                'image' => '0SCDPP1jSRaa5ew1.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 1,
                'gearbox_id' => 1,
                'body_type_id' => 1, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 2,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 1,
                'brand_id' => 3,
                'model_id' => 27,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 10000.00,
                'image' => 'rDYBF3b39uZjIS6t.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 3,
                'gearbox_id' => 1,
                'body_type_id' => 2, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 2,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 5,
                'brand_id' => 3,
                'model_id' => 26,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'price' => 10000.00,
                'image' => 'rsohkgOdH6NqkSxx.jpg',
                'phone_no' => '1234',
                'description' => 'labas',
                'manufacture_date' => '2019-02-02',
                'mileage' => 123321,
                'engine_power' => 160,
                'engine_volume' => 3000.00,
                'damage_id' => 1,
                'fuel_id' => 3,
                'gearbox_id' => 1,
                'body_type_id' => 2, 
                'color_id' =>1,
                'steering_wheel_id' => 1,
                'number_of_doors_id' => 2,
                'driven_wheels_id' => 1,
                'climate_control_id' => 1,
                'euro_standard_id' => 6,
                'brand_id' => 1,
                'model_id' => 18,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
